<form action="/WEB2_TPE/editar/<?=$libro->id_libro?>" method="post">
    Titulo: <input type="text" name="titulo" id="titulo" value="<?=$libro->titulo?>" required>
    Autor: <select name='id_autor' id="id_autor">
        <?php foreach ($autores as $autor){?>
            <option value="<?= $autor->id_autor?>" 
            <?php if($autor->id_autor===$libro->id_autor){
            ?>selected<?php
            }?>>
            <?= $autor->nombre ?></option> /
        <?php } ?>
    </select>
    Género: <input type="text" name="genero" id="genero" value="<?=$libro->genero?>" required>
    Páginas: <input type="number" name="paginas" id="paginas" value="<?=$libro->paginas?>" required>
    <button type="submit">Editar</button>
</form>