<form action="<?php echo BASE_URL ?>/addAutores" method="post">
    <div class="form-row align-items-center">
    <div class="col-auto my-1">
    Nombre: <input class="form-control mb-2 mr-sm-2" type="text" name="nombre" id="nombre" required>
    </div>
    <div class="col-auto my-1">
    Nacimiento: <input class="form-control mb-2 mr-sm-2" type="date" name="nacimiento" id="nacimiento" required>
    </div>
    <div class="col-auto my-1">
    Mail: <input class="form-control mb-2 mr-sm-2" type="email" name="email" id="email" required>
    </div>
    <div class="col-auto my-1">
    <button class="btn btn-primary mb-2" type="submit">Añadir</button>
    </div>
    </div>
</form>