<form action="<?php echo BASE_URL ?>add" method="post">
    <div class="form-row align-items-center">
    <div class="col-auto my-1">
    Titulo: <input class="form-control mb-2 mr-sm-2" type="text" name="titulo" id="titulo" required>
    </div>
    <div class="col-auto my-1">
        Autor: <select class="custom-select mr-sm-2" name='id_autor' id="id_autor">
            <?php foreach ($libros as $autor){?>
                <option value="<?= $autor->id_autor ?>"><?= $autor->nombre ?></option> /
            <?php } ?>
        </select>
    </div>
    <div class="col-auto my-1">
    Género: <input class="form-control mb-2 mr-sm-2" type="text" name="genero" id="genero" required>
    </div>
    <div class="col-auto my-1">
    Páginas: <input class="form-control mb-2 mr-sm-2" type="number" name="paginas" id="paginas" required>
    </div>
    <div class="col-auto my-1">
    <button class="btn btn-primary mb-2" type="submit">Añadir</button>
    </div>
    </div>
</form>