<form action="/WEB2_TPE/add" method="post">
    Titulo: <input type="text" name="titulo" id="titulo" required>
    Autor: <select name='id_autor' id="id_autor">
        <?php foreach ($autores as $autor){?>
            <option value="<?= $autor->id_autor ?>"><?= $autor->nombre ?></option> /
        <?php } ?>
    </select>
    Género: <input type="text" name="genero" id="genero" required>
    Páginas: <input type="number" name="paginas" id="paginas" required>
    <button type="submit">Añadir</button>
</form>