<blockquote class="blockquote text-center">
    <h1><?= $libro->titulo?></h1>
</blockquote>
<table class="table table-striped">
    <thead>
    <tr>
        <td>Autor</td>
        <td>Género</td>
        <td>Páginas</td>
        <?php if (isset($_SESSION['ID_USER'])):?>
        <td></td>  
        <td></td> 
        <?php endif;?> 
    </tr>
    </thead>
    <tr>
            <td><?= $autor->nombre ?> </td> 
            <td><?=$libro->genero?> </td> 
            <td><?=$libro->paginas?> </td>
            <?php if (isset($_SESSION['ID_USER'])):?>
                <td><button class="btn btn-warning" onclick="showAlerta(<?=$libro->id_libro?>);">Borrar</button></td>
                <td><a href="<?php echo BASE_URL ?>edit/<?=$libro->id_libro?>">Editar</a></td>
            <?php endif;?>
    </tr>