<h1><?= $libro->titulo?></h1>
    <table>
        <thead>
            <tr>
                <td></td>
                <td></td>
                <td></td>
            </tr>
        </thead>
        <tr>
            <td>Autor: <?= $autor->nombre ?> </td> 
            <td>Género: <?=$libro->genero?> </td> 
            <td>Páginas: <?=$libro->paginas?> </td>
            <?php if (isset($_SESSION['ID_USER'])):?>
                <td><a href="<?php echo BASE_URL ?>/delete/<?=$libro->id_libro?>">Borrar</a></td>
                <td><a href="<?php echo BASE_URL ?>/edit/<?=$libro->id_libro?>">Editar</a></td>
            <?php endif;?>
        </tr>